# https://finance.yahoo.com/quote/%5ESSMI/components/
SMI = "^SSMI"

# All stocks https://finance.yahoo.com/screener/unsaved/72dc7fe6-0bdb-4c77-8315-52ba6b49a1eb?offset=0&count=100
TICKERS = [
    "NOVN.SW", 
    "SGSN.SW", 
    "UBSG.SW", 
    "ZURN.SW", 
    "GIVN.SW", 
    "NESN.SW", 
    "BAER.SW", 
    "ABBN.SW", 
    "ADEN.SW", 
    "SREN.SW", 
    "SLHN.SW", 
    "CFR.SW", 
    "UHR.SW", 
    "SCMN.SW", 
    "GEBN.SW", 
    "SIKA.SW",
    "LONN.SW", 
    "ROG.SW"
]

# removed 'ASCN.SW'
TICKERS_SW = ['LLY.SW', 'NESNE.SW', 'NESN.SW', 'ROG.SW', 'RO.SW', 'NOVNEE.SW', 'NOVN.SW', 'GE.SW', 'ABBNE.SW', 'ABBN.SW', 'UBSG.SW', 'CFR.SW', 'ZURN.SW', 'HOLNE.SW', 'HOLN.SW', 'SIKA.SW', 'ALC.SW', 'GIVN.SW', 'LONNE.SW', 'LONN.SW', 'SREN.SW', 'KNIN.SW', 'PGHN.SW', 'SCMN.SW', 'LISP.SW', 'LISN.SW', 'SCHN.SW', 'SCHP.SW', 'STMN.SW', 'GEBNE.SW', 'GEBN.SW', 'SLHN.SW', 'NIBEB.SW', 'GALD.SW', 'SOON.SW', 'EMSN.SW', 'SGSN.SW', 'VACN.SW', 'LOGNE.SW', 'LOGN.SW', 'SDZ.SW', 'BAER.SW', 'UHRN.SW', 'UHR.SW', 'BARN.SW', 'BCVN.SW', 'BKW.SW', 'BALN.SW', 'SIGN.SW', 'SPSN.SW', 'HELN.SW', 'FHZN.SW', 'BANB.SW', 'ADEN.SW', 'AVOL.SW', 'YPSN.SW', 'GF.SW', 'PSPN.SW', 'BEAN.SW', 'EMMN.SW', 'SFSN.SW', 'CLN.SW', 'VZN.SW', 'TEMN.SW', 'SQN.SW', 'SUN.SW', 'TECN.SW', 'SFZN.SW', 'EFGNE.SW', 'DKSH.SW', 'EFGN.SW', 'BUCN.SW', 'GALE.SW', 'IFCN.SW', 'DESN.SW', 'ACLN.SW', 'ALSN.SW', 'DAE.SW', 'VONN.SW', 'SRAIL.SW', 'COTN.SW', 'SWON.SW', 'SGKN.SW', 'MOVE.SW', 'ALLN.SW', 'ZUGER.SW', 'INRN.SW', 'BEKN.SW', 'BION.SW', 'LAND.SW', 'CMBN.SW', 'LLBN.SW', 'BCHN.SW', 'BCGE.SW', 'DOKA.SW', 'KARN.SW', 'MOBN.SW', 'SKAN.SW', 'WKBN.SW', 'TXGN.SW', 'ARYN.SW', 'LEHN.SW', 'BELL.SW', 'ZUGN.SW', 'BOSN.SW', 'VATN.SW', 'OERL.SW', 'FORN.SW', 'HBMNE.SW', 'REHN.SW', 'HBMN.SW', 'HUBN.SW', 'AMS.SW', 'AEVS.SW', 'NEAG.SW', 'GRKP.SW', 'IREN.SW', 'VAHN.SW', 'AERO.SW', 'SENS.SW', 'COPN.SW', 'PKTM.SW', 'CFT.SW', 'CFTE.SW', 'ISN.SW', 'JFN.SW', 'PPGN.SW', 'MED.SW', 'BRKN.SW', 'BYS.SW', 'ARBN.SW', 'AUTN.SW', 'KOMN.SW', 'DOCM.SW', 'EPIC.SW', 'HIAG.SW', 'UBXN.SW', 'MEDX.SW', 'VETN.SW', 'PLAN.SW', 'IMPN.SW', 'ZEHN.SW', 'MOZN.SW', 'APGN.SW', 'SWTQ.SW', 'METN.SW', 'RIEN.SW', 'LUKN.SW', 'CPHN.SW', 'SFPN.SW', 'VPBN.SW', 'BSLN.SW', 'TKBP.SW', 'FREN.SW', 'BLKB.SW', 'PMNE.SW', 'PMN.SW', 'STLN.SW', 'LEON.SW', 'WARN.SW', 'IDIA.SW', 'ORON.SW', 'SNBN.SW', 'MTG.SW', 'KURN.SW', 'RSGN.SW', 'VARN.SW', 'VZUG.SW', 'BSKP.SW', 'LECN.SW', 'VBSN.SW', 'MIKN.SW', 'CLTN.SW', 'INA.SW', 'LLQ.SW', 'HBLN.SW', 'GLKBN.SW', 'GURN.SW', 'STGN.SW', 'FTON.SW', 'CALN.SW', 'AFP.SW', 'NREN.SW', 'ODHN.SW', 'ELMN.SW', 'BBN.SW', 'GAV.SW', 'LMN.SW', 'PEAN.SW', 'XLS.SW', 'BVZN.SW', 'PEHN.SW', 'MBTN.SW', 'NWRN.SW', 'BCJ.SW', 'CICN.SW', 'MCHN.SW', 'OFN.SW', 'KLIN.SW', 'TIBN.SW', 'KUD.SW', 'MOLN.SW', 'SANN.SW', 'ESUN.SW', 'ZUBN.SW', 'CLXN.SW', 'SHLTN.SW', 'GMI.SW', 'HLEE.SW', 'ADVN.SW', 'ALPN.SW', 'NBEN.SW', 'VILN.SW', 'CPEN.SW', 'YTME.SW', 'GAM.SW', 'VLRT.SW', 'STRN.SW', 'CURN.SW', 'ASWN.SW', 'WIHN.SW', 'HOCN.SW', 'RLF.SW', 'ADXN.SW', 'EVE.SW', 'ARON.SW', 'AFPE.SW']